let mongoose=require('mongoose')
var userschema=mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    number:{
        type:Number,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    age:{
        type:Number,
        required:true
    },
    size:{
        type:String,
        required:true
    },
    count:{
        type:Number,
        required:true
    },
    dates:{
        type:String,
        required:true
    },
    cases:{
        type:String,
        required:true
    },
    file:{
        type:String,
        required:true
    },
    recepient_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'receipientlogins',
        required:true
    },
    approval:{
        type:Number,
        default:0,
        required:true
    },
    received_amount:{
        type:String,
        default:"0"
    },
    createdAt:{
        type:Date,
        default:Date.now()
    }
})
const Dress=mongoose.model('dressform',userschema)
module.exports={Dress}